import streamlit as st

def publications_page():
  st.write("# Artigos publicados:")
  
  st.write("DA SILVA NETO, SEBASTIAO ROGERIO; DE OLIVEIRA, THOMAS TABOSA ; DE SOUZA SAMPAIO, VANDERSON ; LYNN, THEO ; ENDO, PATRICIA TAKAKO . Platform for monitoring and clinical diagnosis of arboviruses using computational models. In: 2020 International Conference on Cyber Security and Protection of Digital Services (Cyber Security), 2020, Dublin. 2020 International Conference on Cyber Security and Protection of Digital Services (Cyber Security), 2020. p. 1.")
  st.write("OLIVEIRA, T. T. ; SILVA NETO, S. R. ; SAMPAIO, V. ; ENDO, P. T. . Desenvolvimento de um modelo de deep learning para classificação de Dengue e Chikungunya. In: Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2020), 2020, Recife. Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2020), 2020.")
  st.write("SILVA NETO, S. R.; OLIVEIRA, T. T. ; SAMPAIO, V. ; ENDO, P. T. . Monitoramento e diagnóstico clínico de arbovírus utilizando modelos computacionais. In: Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2020), 2020, Recife. Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2020), 2020.")
  st.write("DE OLIVEIRA, THOMÁS TABOSA ; DA SILVA NETO, SEBASTIÃO ROGÉRIO ; TEIXEIRA, IGOR VITOR ; ENDO, PATRICIA TAKAKO ; SAMPAIO, VANDERSON SOUZA . VALERIA: Uma Plataforma para Auxiliar o Diagnóstico e o Monitoramento de Arboviroses. In: Anais Estendidos do Simpósio Brasileiro de Sistemas Multimídia e Web, 2021, Brasil. Anais Estendidos do XXVII Simpósio Brasileiro de Sistemas Multimídia e Web (WebMedia 2021). p. 103.")
  st.write("SILVA NETO, S. R.; OLIVEIRA, T. T. ; SAMPAIO, V. ; ENDO, P. T. . Técnicas de machine learning e deep learning para o apoio do diagnóstico clínico de arboviroses: uma revisão sistemática. In: Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2021), 2021, Recife. Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2021), 2021.")
  st.write("OLIVEIRA, T. T. ; SILVA NETO, S. R. ; SAMPAIO, V. ; ENDO, PATRICIA TAKAKO . Classificação multi-classe de arboviroses utilizando Extra Trees. In: Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2021), 2021, Recife. Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2021), 2021.")
  st.write("DA SILVA NETO, SEBASTIÃO ROGÉRIO; TABOSA OLIVEIRA, THOMÁS ; TEIXEIRA, IGOR VITOR ; AGUIAR DE OLIVEIRA, SAMUEL BENJAMIN ; SOUZA SAMPAIO, VANDERSON ; LYNN, THEO ; ENDO, PATRICIA TAKAKO . Machine learning and deep learning techniques to support clinical diagnosis of arboviral diseases: A systematic review. PLoS Neglected Tropical Diseases, v. 16, p. e0010061, 2022.")
  st.write("DA SILVA NETO, SEBASTIÃO ROGÉRIO; TABOSA DE OLIVEIRA, THOMÁS ; TEIXIERA, IGOR VITOR ; MEDEIROS NETO, LEONIDES ; SOUZA SAMPAIO, VANDERSON ; LYNN, THEO ; ENDO, PATRICIA TAKAKO . Arboviral disease record data - Dengue and Chikungunya, Brazil, 2013-2020. Scientific Data, v. 9, p. 198, 2022.")
  st.write("TABOSA DE OLIVEIRA, THOMÁS ; DA SILVA NETO, SEBASTIÃO ROGÉRIO ; TEIXEIRA, IGOR VITOR ; AGUIAR DE OLIVEIRA, SAMUEL BENJAMIN ; DE ALMEIDA RODRIGUES, MARIA GABRIELA ; SAMPAIO, VANDERSON SOUZA ; ENDO, PATRICIA TAKAKO . A Comparative Study of Machine Learning Techniques for Multi-Class Classification of Arboviral Diseases. Frontiers in Tropical Diseases, v. 2, p. 1, 2022.")
  st.write("MELLO, M. E. F. ; SILVA NETO, S. R. ; ENDO, PATRICIA TAKAKO . Utilização de modelos de machine learning como ferramenta auxiliar no diagnóstico de Chikungunya. In: 10ª Semana de Biociências e Biotecnologia em Saúde, 2022, Recife. 10ª Semana de Biociências e Biotecnologia em Saúde, 2022, 2022.")
  st.write("SILVA NETO, S. R.; OLIVEIRA, T. T. ; MEDEIROS NETO, LEONIDES ; SAMPAIO, V. ; ENDO, PATRICIA TAKAKO . Ensemble stacking para classificação multi-classe de arboviroses. In: Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2022), 2022, Recife. Mostra de Extensão, Inovação e Pesquisa da Escola Politécnica da Universidade de Pernambuco (MOSTRA POLI 2022), 2022.")
  st.write("SILVA NETO, S. R.; OLIVEIRA, T. T. ; TEIXEIRA, I. V. ; MEDEIROS NETO, LEONIDES ; SADOK, SARA ; SAMPAIO, V. ; ENDO, PATRICIA TAKAKO . Binary Models for Arboviruses Classification Using Machine Learning: A Benchmarking Evaluation. In: Hawaii International Conference on System Sciences (HICSS), 2023, Maui. Proceedings of the 56th Hawaii International Conference on System Sciences, 2023, 2023.")